In [1]:
import pandas as pd
import numpy as np

In [5]:
data=pd.read_csv('/content/Sample - Superstore.csv',encoding='ISO-8859-1')

In [6]:
data.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
# Mengecek jumlah nilai null pada setiap kolom
null_data = data.isnull().sum()

# Menampilkan kolom-kolom dengan nilai null
print(null_data)

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [8]:
# Menampilkan baris yang memiliki nilai null
rows_with_null = data[data.isnull().any(axis=1)]

print(rows_with_null)

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit]
Index: []

[0 rows x 21 columns]

In [13]:

# Memeriksa apakah ada string kosong di kolom 'Profit'
blank_profit = data['Profit'] == ''

# Menampilkan jumlah baris dengan string kosong pada kolom 'Profit'
print("Jumlah baris dengan string kosong di kolom 'Profit':", blank_profit.sum())

Jumlah baris dengan string kosong di kolom 'Profit': 0

In [16]:
# Mengonversi kolom 'Order Date' dan 'Ship Date' menjadi tipe data datetime
data['Order Date'] = pd.to_datetime(data['Order Date'], errors='coerce')
data['Ship Date'] = pd.to_datetime(data['Ship Date'], errors='coerce')

# Mengubah format tanggal sehingga bulan menjadi dua digit (MM)
data['Order Date'] = data['Order Date'].dt.strftime('%Y-%m-%d')  # Menjaga format 'YYYY-MM-DD'
data['Ship Date'] = data['Ship Date'].dt.strftime('%Y-%m-%d')    # Menjaga format 'YYYY-MM-DD'

# Menampilkan beberapa baris pertama untuk memeriksa perubahan
print(data[['Order Date', 'Ship Date']].head())

   Order Date   Ship Date
0  2016-11-08  2016-11-11
1  2016-11-08  2016-11-11
2  2016-06-12  2016-06-16
3  2015-10-11  2015-10-18
4  2015-10-11  2015-10-18

In [17]:

# Menyimpan dataset yang telah dimodifikasi ke file Excel
data.to_excel('modified_sample_superstore.xlsx', index=False, engine='openpyxl')

print("File baru telah disimpan dengan nama 'modified_sample_superstore.xlsx'")

File baru telah disimpan dengan nama 'modified_sample_superstore.xlsx'